import './globals.css';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children, params, locale }) {
  console.log("PROPS", params, locale)
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
